### ISSUE TITLE
Receiving model not found running "python3 code/zero-shot.py --Codex=True --Do_MATH=True"

### ISSUE THREAD

**Issue by dd4gg** [idrori/mathQ#1]
I am receiving the following error when I try to run the zero-shot for the MATH benchmark:

```
python3 code/zero-shot.py --Codex=True --Do_MATH=True
Running Zero-Shot on MATH_Algebra question 1...
Traceback (most recent call last):
  File "/Users/myuser/programs/mathQ/code/zero-shot.py", line 155, in <module>
    execute_zero_shot(MATH_sections_to_zero_shot, questions_per_MATH_section, 
  File "/Users/myuser/programs/mathQ/code/zero-shot.py", line 103, in execute_zero_shot
    codex_output = openai.Completion.create(engine = codex_engine, 
  File "/opt/homebrew/lib/python3.9/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 115, in create
    response, _, api_key = requestor.request(
  File "/opt/homebrew/lib/python3.9/site-packages/openai/api_requestor.py", line 121, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/opt/homebrew/lib/python3.9/site-packages/openai/api_requestor.py", line 328, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/lib/python3.9/site-packages/openai/api_requestor.py", line 361, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist
```

Running Python 3.9.13 64-bit on Mac OS with M1 Monterey 12.5.1. Any suggestions?

**Comment by JarJarBeatU** [comment]
I think the issue is that the code uses code davinci, (codex) which is still in private beta. You can apply here: https://share.hsforms.com/1GzaACuXwSsmLKPfmphF_1w4sk30?
